import logging

from uuid import UUID

from app.services.reranking.cross_encoder_service import CrossEncoderService
from app.services.embeddings.embedding_service import EmbeddingService
from app.services.vector_store.vectorstore_service import VectorStoreService
from app.services.retrieval.schemas import RetrievedChunk, ChatResponse, SearchResponse
from app.services.builder.context_builder import ContextBuilder
from app.services.builder.prompt_builder import PromptBuilder
from app.services.llm.llm_service import LLMService

logger = logging.getLogger(__name__)


class RetrievalService:

    def __init__(self):
        self.embedding_service = EmbeddingService()
        self.vector_store = VectorStoreService()
        self.cross_encoder_service = CrossEncoderService()
        self.context_builder = ContextBuilder()
        self.prompt_builder = PromptBuilder()
        self.llm_service = LLMService()

    async def ask(
            self,
            query: str,
            transcript_id: UUID | None = None,
            user_id: UUID | None = None,
            retrieve_top_k: int = 20,
            rerank_top_k: int = 5
    ) -> str:
        """
        Ask a question and get an answer based on the provided query.

        Args:
            query (str): The search query.
            transcript_id (UUID | None): Optional transcript ID to filter results.
            user_id (UUID | None): Optional user ID to filter results.
            retrieve_top_k (int): The number of top results to retrieve.
            rerank_top_k (int): The number of top results to rerank.

        Returns:
            str: The answer generated by the LLM based on the query and context.
        """
        try:
            # Generate embedding for the query
            logger.info(f"Generating embedding for query..............")
            chunks = await self.search(
                query=query,
                transcript_id=transcript_id,
                user_id=user_id,
                retrieve_top_k=retrieve_top_k,
                rerank_top_k=rerank_top_k
            )
            
            # Build context from the retrieved chunks
            context = self.context_builder.build(chunks, transcript_id=transcript_id, user_id=user_id)
            logger.info(f"Context built successfully................")
            # Build prompt for the LLM using the query and context
            messages = self.prompt_builder.build(
                query=query,
                context=context,
            )

            # Generate response from the LLM based on the prompt
            logger.info(f"Generating response from LLM..............")
            LLM_response = self.llm_service.generate_response(messages=messages)

            return ChatResponse(
                answer=LLM_response.answer,
                chunks=chunks
            )
        
        except Exception as e:
            logger.exception(f"Error occurred during ask: {e}")
            raise RuntimeError(f"Error occurred during ask: {e}")
    
    async def search(
            self,
            query: str,
            transcript_id: UUID | None = None,
            user_id: UUID | None = None,
            retrieve_top_k: int = 20,
            rerank_top_k: int = 5
    ) -> list[RetrievedChunk]:
        """
        Search for relevant information based on the provided query.

        Args:
            query (str): The search query.
            transcript_id (UUID | None): Optional transcript ID to filter results.
            user_id (UUID | None): Optional user ID to filter results.
            top_k (int): The number of top results to return.

        Returns:
            list[RetrievedChunk]: A list of relevant search results.
        """
        try:
            # Generate embedding for the query
            logger.info(f"Generating embedding for query..............")
            query_embedding = await self.embedding_service.embed_query(query)

            # Build the filter for the search based on transcript_id and user_id
            where = self._build_where_filter(transcript_id, user_id)

            logger.info(f"Searching for relevant information..............")
            
            # Perform the search in the vector store
            results = await self.vector_store.search(
                query_embedding=query_embedding,
                where=where,
                top_k=retrieve_top_k,
            )

            # Process the search results and create RetrievedChunk objects
            search_results = []

            documents = results["documents"][0]
            metadatas = results["metadatas"][0]
            distances = results["distances"][0]

            for doc, metadata, distance in zip(documents, metadatas, distances):
                search_results.append(
                    RetrievedChunk(
                        document=doc,
                        distance=distance,
                        transcript_id=UUID(metadata["transcript_id"]),
                        chunk_index=metadata["chunk_index"],
                        filename=metadata["filename"],
                    )
                )

            logger.info(f"Search completed. Found {len(search_results)} results.")

            # Rerank the search results using the cross-encoder service
            logger.info(f"Reranking the search results..............")
            chunks = await self.cross_encoder_service.rerank(
                query=query,
                results=search_results, 
                top_k=rerank_top_k)
            
            logger.info(f"Reranking completed. Returning top {len(chunks)} results.")

            return chunks
        except Exception as e:
            logger.exception(f"Error occurred during search: {e}")
            raise RuntimeError(f"Error occurred during search: {e}")

    def _build_where_filter(
        self,
        transcript_id: UUID | None,
        user_id: UUID | None,
    ) -> dict | None:

        where = {}

        if transcript_id and user_id:
            where = {
                "$and": [
                    {"transcript_id": str(transcript_id)},
                    {"user_id": str(user_id)},
                ]
            }

        return where or None